#pragma once
#include <cstdint>
#include <filesystem>
#include <map>
#include <optional>
#include <string>
namespace worldgen {
struct ResolutionConfig{int width=768,height=384,history_step_myr=25,history_myr=850;};
struct NoiseConfig{int octaves=7;double persistence=.56,lacunarity=2,domain_warp_strength=.32,minimum_sigma_px=.52,value_weight=.44,ridge_weight=.25,billow_weight=.16,wave_weight=.15;int wave_count=5;};
struct AstronomyConfig{double star_mass_solar=.92,planet_mass_earth=1,planet_density_g_cm3=5.45;std::optional<double>semimajor_axis_au{};double eccentricity=.025,longitude_periapsis_deg=103,axial_tilt_deg=23,rotation_hours=24.8,albedo=.3,greenhouse_k=33,target_mean_surface_c=15,moon_mass_earth=.0123,moon_orbit_km=385000,atmosphere_pressure_bar=1;int system_planet_count=8;double stellar_neighborhood_radius_ly=20,stellar_density_per_ly3=.004;std::map<std::string,double>atmosphere{{"N2",.78},{"O2",.209},{"Ar",.0093},{"CO2",.0006}};};
struct TectonicsConfig{int plate_count=14;double continental_fraction_target=.29,continental_plate_fraction=.47,max_plate_speed_cm_yr=8;int hotspot_count=22;double lip_interval_myr=16,mountain_uplift_km=5,ridge_uplift_km=2.3,trench_depth_km=4,terrain_noise_km=.55,mean_subplates_per_plate=5;int min_subplates_per_plate=3,max_subplates_per_plate=9;double subplate_motion_dispersion=.32,parent_coupling=.68,collision_nudge=.10,split_stress_threshold=1.35,fuse_direction_deg=15;int fuse_persistence_steps=3;double boundary_warp_deg=4.8;int boundary_detail_octaves=6,boundary_deformation_iterations=2;double strain_boundary_warp_deg=2.6;int shape_control_points_per_subplate=2;double shape_control_spread_deg=5;int history_grid_height=96;};
struct TerrainConfig{std::string sea_level_mode="target_land_fraction";double erosion_m_per_myr=4.6,lapse_rate_k_per_km=6.5,shelf_depth_m=200,shelf_width_km_passive=140,shelf_width_km_active=55;int fractal_octaves=7;double relief_detail_strength=.42,fault_block_relief_km=.75,rift_shoulder_uplift_km=.85,coastal_reworking_strength=.20,coastal_reworking_sigma_px=.85,coastal_reworking_band_km=.22,min_island_area_km2=900;};
struct OceanConfig{double young_crust_depth_m=2600,subsidence_sqrt_m_per_sqrt_myr=350,max_abyss_depth_m=6200;int current_iterations=36;double wind_coupling=.55,gyre_strength=2.35,ekman_strength=.28,seasonal_current_strength=.72;int heat_transport_iterations=8;double heat_advection_strength=.42,heat_diffusion_sigma=.75,sst_transport_gain=8,western_boundary_strength=.58,eastern_boundary_strength=.18,bathymetric_steering_strength=.28,boundary_current_width_km=420,abyssal_relief_noise_m=150;};
struct ClimateConfig{int months=12;double continentality_k=28;int moisture_iterations=30;double precip_scale_mm_year=1100,orographic_strength=2.35,orographic_lift_scale_km=.42,pressure_land_seasonality=5,precipitation_softscale_mm_month=520,precipitation_tail_exponent=.64,precipitation_extreme_softcap_mm_month=1350,inland_thermal_length_km=1800,ocean_seasonal_response_c=5.5,moisture_step_km=190,trade_wind_strength=1.05,westerly_strength=.78,polar_easterly_strength=.48,seasonal_itcz_shift_fraction=.62,humidity_temperature_sensitivity=.055,land_thermal_lag_months=.85,ocean_thermal_lag_months=3.2;int thermal_memory_spinup_years=5;double hadley_meridional_strength=.54,ferrel_meridional_strength=.16,stationary_wave_strength=.34,topographic_wind_steering=.18,climate_texture_c=.85,convective_texture_strength=.18,precipitation_mesoscale_sigma_px=1.2;};
struct HydrologyConfig{double river_accumulation_quantile=.985,min_river_precip_mm_year=120,min_drainage_area_km2=520,runoff_base_fraction=.24;int surface_evolution_iterations=4;std::string flow_refresh_mode="interval";int flow_refresh_interval=1,flow_refresh_max_interval=3;double flow_refresh_elevation_threshold_m=4,flow_refresh_land_change_fraction=2e-4,flow_refresh_delta_threshold_m=2,stream_power_m=.5,stream_power_n=1,max_fluvial_erosion_m_per_iteration=15,hillslope_diffusion_strength=.028,deposition_strength=.54;int sediment_routing_passes=16;double river_meander_strength=.95,meander_slope_scale=.0019,lateral_erosion_fraction=.34,meander_microrelief_m=12,delta_retention_fraction=.52,delta_max_depth_m=180,delta_spread_cells=2.2,delta_max_aggradation_m_per_iteration=18,delta_min_outlet_discharge_norm=.28,tectonic_uplift_m_per_iteration=4.5,rift_subsidence_m_per_iteration=1.8,lake_min_depth_m=5,lake_min_catchment_km2=350,lake_area_soft_cap_fraction_land=.022,tributary_discharge_fraction=.28;int max_river_centerlines=180;double delta_wave_reworking_strength=.32,delta_tide_reworking_strength=.16,delta_shelf_slope_scale=.0016,delta_distributary_texture_strength=.26;};
struct SimulationConfig{int earth_system_passes=3,final_climate_ocean_passes=1;double intermediate_climate_fraction=.28,intermediate_ocean_fraction=.52;bool preserve_initial_sea_level=true,adaptive_convergence=false;int min_earth_system_passes=2,max_earth_system_passes=6;double convergence_temperature_c=.15,convergence_precip_mm_year=15,convergence_elevation_m=2;int required_consecutive_converged_passes=2;bool adaptive_final_coupling=false;int min_final_climate_ocean_passes=1,max_final_climate_ocean_passes=4;double final_convergence_temperature_c=.08,final_convergence_precip_mm_year=8;int required_consecutive_final_converged_passes=1;};
struct WeatherConfig{double hurricane_sst_c=26.5,hurricane_lat_min_deg=5,hurricane_lat_max_deg=35;int hurricane_seed_count=40,hurricane_max_steps=100;};
struct ResourcesConfig{double deposit_density=1;int meteorite_expected_count=3;};
struct SocietyConfig{bool enabled=true;int settlement_count=80,history_years=2200,history_step_years=25;bool portal_prefer_mountains=true;double portal_latitude_max_deg=55,agricultural_productivity_weight=.22,river_navigation_bonus=.10,coastal_trade_bonus=.06;};
struct AppearanceConfig{double vegetation_temp_mid_c=7,vegetation_temp_scale_c=6.5,forest_precip_mid_mm_year=850,forest_precip_scale_mm_year=420,alpine_bare_start_km=2.6,alpine_bare_full_km=5.2,snow_albedo=.78,vegetation_albedo=.16,desert_albedo=.31,ocean_albedo=.065,turbidity_spread_sigma_px=3.2,turbidity_strength=.78,hillshade_strength=.30,cloud_smoothing_sigma_px=.85,cloud_max_optical_opacity=.72,cloud_humidity_mid=.13,cloud_precip_mid_mm_month=45;};
struct OutputConfig{bool save_npz=true,save_png=true,save_json=true,save_report=true,compress_npz=false;int map_dpi=120,rgb_dpi=135;};
struct WorldConfig{
 std::uint64_t seed=20260826;ResolutionConfig resolution;AstronomyConfig astronomy;NoiseConfig noise;TectonicsConfig tectonics;TerrainConfig terrain;OceanConfig ocean;ClimateConfig climate;HydrologyConfig hydrology;SimulationConfig simulation;WeatherConfig weather;ResourcesConfig resources;SocietyConfig society;AppearanceConfig appearance;OutputConfig output;
 void validate()const; static WorldConfig load_yaml(const std::filesystem::path&); void apply_override(const std::string&expr);
};
} // namespace worldgen
