#include "worldgen/config.hpp"
#include <algorithm>
#include <charconv>
#include <cmath>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string_view>
#include <unordered_map>
#include <vector>
#include <limits>
#include <cctype>
namespace worldgen {
namespace {
std::string trim(std::string s){auto notsp=[](unsigned char c){return !std::isspace(c);};s.erase(s.begin(),std::find_if(s.begin(),s.end(),notsp));s.erase(std::find_if(s.rbegin(),s.rend(),notsp).base(),s.end());return s;}
double number(const std::string&v){std::size_t p=0;double x=std::stod(v,&p);if(p!=v.size()||!std::isfinite(x))throw std::invalid_argument("invalid number: "+v);return x;}
int integer(const std::string&v){std::size_t p=0;long long x=std::stoll(v,&p);if(p!=v.size()||x<std::numeric_limits<int>::min()||x>std::numeric_limits<int>::max())throw std::invalid_argument("invalid integer: "+v);return static_cast<int>(x);}
bool boolean(std::string v){if(v=="true"||v=="True")return true;if(v=="false"||v=="False")return false;throw std::invalid_argument("invalid boolean: "+v);}
void req(bool ok,const char*msg){if(!ok)throw std::invalid_argument(msg);} void fin(double x,const char*msg){if(!std::isfinite(x))throw std::invalid_argument(msg);}
}
void WorldConfig::validate()const{
 req(resolution.width>=64&&resolution.height>=32,"resolution too small");req(resolution.width==2*resolution.height,"resolution must be 2:1");req(resolution.history_step_myr>0&&resolution.history_step_myr<=resolution.history_myr,"invalid tectonic history sampling");
 req(noise.octaves>=1&&noise.octaves<=16,"noise.octaves out of range");req(noise.persistence>0&&noise.persistence<1,"noise.persistence out of range");req(noise.lacunarity>1,"noise.lacunarity must exceed one");req(noise.wave_count>=2&&noise.wave_count<=64,"noise.wave_count out of range");
 req(astronomy.star_mass_solar>0&&astronomy.planet_mass_earth>0&&astronomy.planet_density_g_cm3>0&&astronomy.rotation_hours>0&&astronomy.atmosphere_pressure_bar>0,"invalid astronomy positive parameter");req(astronomy.eccentricity>=0&&astronomy.eccentricity<.95,"invalid eccentricity");req(astronomy.albedo>=0&&astronomy.albedo<=1,"invalid albedo");req(!astronomy.atmosphere.empty(),"atmosphere empty");double asum=0;for(auto&[k,v]:astronomy.atmosphere){req(!k.empty()&&v>=0,"invalid atmosphere component");asum+=v;}req(asum>0,"atmosphere sum must be positive");
 req(tectonics.plate_count>=2&&tectonics.plate_count<=32766,"plate_count out of range");req(tectonics.continental_fraction_target>=0&&tectonics.continental_fraction_target<=1,"land fraction out of range");req(tectonics.min_subplates_per_plate>=1&&tectonics.max_subplates_per_plate>=tectonics.min_subplates_per_plate,"subplate bounds invalid");
 req(terrain.sea_level_mode=="target_land_fraction","unsupported sea level mode");req(climate.months==12,"climate currently requires 12 months");req(climate.moisture_iterations>0,"moisture_iterations must be positive");
 req(hydrology.flow_refresh_mode=="interval"||hydrology.flow_refresh_mode=="adaptive"||hydrology.flow_refresh_mode=="hybrid","invalid flow refresh mode");req(hydrology.flow_refresh_interval>=1&&hydrology.flow_refresh_max_interval>=1,"invalid flow refresh interval");
 req(simulation.earth_system_passes>=1&&simulation.final_climate_ocean_passes>=1,"invalid simulation passes");req(simulation.min_earth_system_passes>=1&&simulation.max_earth_system_passes>=simulation.min_earth_system_passes,"invalid adaptive pass range");
 fin(ocean.max_abyss_depth_m,"nonfinite ocean config");fin(climate.precip_scale_mm_year,"nonfinite climate config");fin(hydrology.stream_power_m,"nonfinite hydrology config");
}
void WorldConfig::apply_override(const std::string&e){auto pos=e.find('=');if(pos==std::string::npos)throw std::invalid_argument("override must be path=value");const std::string k=trim(e.substr(0,pos)),v=trim(e.substr(pos+1));
#define SETI(path,field) if(k==path){field=integer(v);return;}
#define SETD(path,field) if(k==path){field=number(v);return;}
#define SETB(path,field) if(k==path){field=boolean(v);return;}
#define SETS(path,field) if(k==path){field=v;return;}
 if(k=="seed"){seed=static_cast<std::uint64_t>(std::stoull(v));return;}
 SETI("resolution.width",resolution.width) SETI("resolution.height",resolution.height) SETI("resolution.history_step_myr",resolution.history_step_myr) SETI("resolution.history_myr",resolution.history_myr)
 SETI("noise.octaves",noise.octaves) SETD("noise.persistence",noise.persistence) SETD("noise.lacunarity",noise.lacunarity) SETD("noise.domain_warp_strength",noise.domain_warp_strength) SETD("noise.minimum_sigma_px",noise.minimum_sigma_px) SETD("noise.value_weight",noise.value_weight) SETD("noise.ridge_weight",noise.ridge_weight) SETD("noise.billow_weight",noise.billow_weight) SETD("noise.wave_weight",noise.wave_weight) SETI("noise.wave_count",noise.wave_count)
 SETD("astronomy.star_mass_solar",astronomy.star_mass_solar) SETD("astronomy.planet_mass_earth",astronomy.planet_mass_earth) SETD("astronomy.planet_density_g_cm3",astronomy.planet_density_g_cm3) if(k=="astronomy.semimajor_axis_au"){astronomy.semimajor_axis_au=(v=="null"?std::optional<double>{}:std::optional<double>{number(v)});return;} SETD("astronomy.eccentricity",astronomy.eccentricity) SETD("astronomy.longitude_periapsis_deg",astronomy.longitude_periapsis_deg) SETD("astronomy.axial_tilt_deg",astronomy.axial_tilt_deg) SETD("astronomy.rotation_hours",astronomy.rotation_hours) SETD("astronomy.albedo",astronomy.albedo) SETD("astronomy.greenhouse_k",astronomy.greenhouse_k) SETD("astronomy.target_mean_surface_c",astronomy.target_mean_surface_c) SETD("astronomy.moon_mass_earth",astronomy.moon_mass_earth) SETD("astronomy.moon_orbit_km",astronomy.moon_orbit_km) SETD("astronomy.atmosphere_pressure_bar",astronomy.atmosphere_pressure_bar) SETI("astronomy.system_planet_count",astronomy.system_planet_count) SETD("astronomy.stellar_neighborhood_radius_ly",astronomy.stellar_neighborhood_radius_ly) SETD("astronomy.stellar_density_per_ly3",astronomy.stellar_density_per_ly3)
 if(k.rfind("astronomy.atmosphere.",0)==0){astronomy.atmosphere[k.substr(21)]=number(v);return;}
 SETI("tectonics.plate_count",tectonics.plate_count) SETD("tectonics.continental_fraction_target",tectonics.continental_fraction_target) SETD("tectonics.continental_plate_fraction",tectonics.continental_plate_fraction) SETD("tectonics.max_plate_speed_cm_yr",tectonics.max_plate_speed_cm_yr) SETI("tectonics.hotspot_count",tectonics.hotspot_count) SETD("tectonics.lip_interval_myr",tectonics.lip_interval_myr) SETD("tectonics.mountain_uplift_km",tectonics.mountain_uplift_km) SETD("tectonics.ridge_uplift_km",tectonics.ridge_uplift_km) SETD("tectonics.trench_depth_km",tectonics.trench_depth_km) SETD("tectonics.terrain_noise_km",tectonics.terrain_noise_km) SETD("tectonics.mean_subplates_per_plate",tectonics.mean_subplates_per_plate) SETI("tectonics.min_subplates_per_plate",tectonics.min_subplates_per_plate) SETI("tectonics.max_subplates_per_plate",tectonics.max_subplates_per_plate) SETD("tectonics.subplate_motion_dispersion",tectonics.subplate_motion_dispersion) SETD("tectonics.parent_coupling",tectonics.parent_coupling) SETD("tectonics.collision_nudge",tectonics.collision_nudge) SETD("tectonics.split_stress_threshold",tectonics.split_stress_threshold) SETD("tectonics.fuse_direction_deg",tectonics.fuse_direction_deg) SETI("tectonics.fuse_persistence_steps",tectonics.fuse_persistence_steps) SETD("tectonics.boundary_warp_deg",tectonics.boundary_warp_deg) SETI("tectonics.boundary_detail_octaves",tectonics.boundary_detail_octaves) SETI("tectonics.boundary_deformation_iterations",tectonics.boundary_deformation_iterations) SETD("tectonics.strain_boundary_warp_deg",tectonics.strain_boundary_warp_deg) SETI("tectonics.shape_control_points_per_subplate",tectonics.shape_control_points_per_subplate) SETD("tectonics.shape_control_spread_deg",tectonics.shape_control_spread_deg) SETI("tectonics.history_grid_height",tectonics.history_grid_height)
 SETS("terrain.sea_level_mode",terrain.sea_level_mode) SETD("terrain.erosion_m_per_myr",terrain.erosion_m_per_myr) SETD("terrain.lapse_rate_k_per_km",terrain.lapse_rate_k_per_km) SETD("terrain.shelf_depth_m",terrain.shelf_depth_m) SETD("terrain.shelf_width_km_passive",terrain.shelf_width_km_passive) SETD("terrain.shelf_width_km_active",terrain.shelf_width_km_active) SETI("terrain.fractal_octaves",terrain.fractal_octaves) SETD("terrain.relief_detail_strength",terrain.relief_detail_strength) SETD("terrain.fault_block_relief_km",terrain.fault_block_relief_km) SETD("terrain.rift_shoulder_uplift_km",terrain.rift_shoulder_uplift_km) SETD("terrain.coastal_reworking_strength",terrain.coastal_reworking_strength) SETD("terrain.coastal_reworking_sigma_px",terrain.coastal_reworking_sigma_px) SETD("terrain.coastal_reworking_band_km",terrain.coastal_reworking_band_km) SETD("terrain.min_island_area_km2",terrain.min_island_area_km2)
 SETD("ocean.young_crust_depth_m",ocean.young_crust_depth_m) SETD("ocean.subsidence_sqrt_m_per_sqrt_myr",ocean.subsidence_sqrt_m_per_sqrt_myr) SETD("ocean.max_abyss_depth_m",ocean.max_abyss_depth_m) SETI("ocean.current_iterations",ocean.current_iterations) SETD("ocean.wind_coupling",ocean.wind_coupling) SETD("ocean.gyre_strength",ocean.gyre_strength) SETD("ocean.ekman_strength",ocean.ekman_strength) SETD("ocean.seasonal_current_strength",ocean.seasonal_current_strength) SETI("ocean.heat_transport_iterations",ocean.heat_transport_iterations) SETD("ocean.heat_advection_strength",ocean.heat_advection_strength) SETD("ocean.heat_diffusion_sigma",ocean.heat_diffusion_sigma) SETD("ocean.sst_transport_gain",ocean.sst_transport_gain) SETD("ocean.western_boundary_strength",ocean.western_boundary_strength) SETD("ocean.eastern_boundary_strength",ocean.eastern_boundary_strength) SETD("ocean.bathymetric_steering_strength",ocean.bathymetric_steering_strength) SETD("ocean.boundary_current_width_km",ocean.boundary_current_width_km) SETD("ocean.abyssal_relief_noise_m",ocean.abyssal_relief_noise_m)
 SETI("climate.months",climate.months) SETD("climate.continentality_k",climate.continentality_k) SETI("climate.moisture_iterations",climate.moisture_iterations) SETD("climate.precip_scale_mm_year",climate.precip_scale_mm_year) SETD("climate.orographic_strength",climate.orographic_strength) SETD("climate.orographic_lift_scale_km",climate.orographic_lift_scale_km) SETD("climate.pressure_land_seasonality",climate.pressure_land_seasonality) SETD("climate.precipitation_softscale_mm_month",climate.precipitation_softscale_mm_month) SETD("climate.precipitation_tail_exponent",climate.precipitation_tail_exponent) SETD("climate.precipitation_extreme_softcap_mm_month",climate.precipitation_extreme_softcap_mm_month) SETD("climate.inland_thermal_length_km",climate.inland_thermal_length_km) SETD("climate.ocean_seasonal_response_c",climate.ocean_seasonal_response_c) SETD("climate.moisture_step_km",climate.moisture_step_km) SETD("climate.trade_wind_strength",climate.trade_wind_strength) SETD("climate.westerly_strength",climate.westerly_strength) SETD("climate.polar_easterly_strength",climate.polar_easterly_strength) SETD("climate.seasonal_itcz_shift_fraction",climate.seasonal_itcz_shift_fraction) SETD("climate.humidity_temperature_sensitivity",climate.humidity_temperature_sensitivity) SETD("climate.land_thermal_lag_months",climate.land_thermal_lag_months) SETD("climate.ocean_thermal_lag_months",climate.ocean_thermal_lag_months) SETI("climate.thermal_memory_spinup_years",climate.thermal_memory_spinup_years) SETD("climate.hadley_meridional_strength",climate.hadley_meridional_strength) SETD("climate.ferrel_meridional_strength",climate.ferrel_meridional_strength) SETD("climate.stationary_wave_strength",climate.stationary_wave_strength) SETD("climate.topographic_wind_steering",climate.topographic_wind_steering) SETD("climate.climate_texture_c",climate.climate_texture_c) SETD("climate.convective_texture_strength",climate.convective_texture_strength) SETD("climate.precipitation_mesoscale_sigma_px",climate.precipitation_mesoscale_sigma_px)
 SETD("hydrology.river_accumulation_quantile",hydrology.river_accumulation_quantile) SETD("hydrology.min_river_precip_mm_year",hydrology.min_river_precip_mm_year) SETD("hydrology.min_drainage_area_km2",hydrology.min_drainage_area_km2) SETD("hydrology.runoff_base_fraction",hydrology.runoff_base_fraction) SETI("hydrology.surface_evolution_iterations",hydrology.surface_evolution_iterations) SETS("hydrology.flow_refresh_mode",hydrology.flow_refresh_mode) SETI("hydrology.flow_refresh_interval",hydrology.flow_refresh_interval) SETI("hydrology.flow_refresh_max_interval",hydrology.flow_refresh_max_interval) SETD("hydrology.flow_refresh_elevation_threshold_m",hydrology.flow_refresh_elevation_threshold_m) SETD("hydrology.flow_refresh_land_change_fraction",hydrology.flow_refresh_land_change_fraction) SETD("hydrology.flow_refresh_delta_threshold_m",hydrology.flow_refresh_delta_threshold_m) SETD("hydrology.stream_power_m",hydrology.stream_power_m) SETD("hydrology.stream_power_n",hydrology.stream_power_n) SETD("hydrology.max_fluvial_erosion_m_per_iteration",hydrology.max_fluvial_erosion_m_per_iteration) SETD("hydrology.hillslope_diffusion_strength",hydrology.hillslope_diffusion_strength) SETD("hydrology.deposition_strength",hydrology.deposition_strength) SETI("hydrology.sediment_routing_passes",hydrology.sediment_routing_passes) SETD("hydrology.river_meander_strength",hydrology.river_meander_strength) SETD("hydrology.meander_slope_scale",hydrology.meander_slope_scale) SETD("hydrology.lateral_erosion_fraction",hydrology.lateral_erosion_fraction) SETD("hydrology.meander_microrelief_m",hydrology.meander_microrelief_m) SETD("hydrology.delta_retention_fraction",hydrology.delta_retention_fraction) SETD("hydrology.delta_max_depth_m",hydrology.delta_max_depth_m) SETD("hydrology.delta_spread_cells",hydrology.delta_spread_cells) SETD("hydrology.delta_max_aggradation_m_per_iteration",hydrology.delta_max_aggradation_m_per_iteration) SETD("hydrology.delta_min_outlet_discharge_norm",hydrology.delta_min_outlet_discharge_norm) SETD("hydrology.tectonic_uplift_m_per_iteration",hydrology.tectonic_uplift_m_per_iteration) SETD("hydrology.rift_subsidence_m_per_iteration",hydrology.rift_subsidence_m_per_iteration) SETD("hydrology.lake_min_depth_m",hydrology.lake_min_depth_m) SETD("hydrology.lake_min_catchment_km2",hydrology.lake_min_catchment_km2) SETD("hydrology.lake_area_soft_cap_fraction_land",hydrology.lake_area_soft_cap_fraction_land) SETD("hydrology.tributary_discharge_fraction",hydrology.tributary_discharge_fraction) SETI("hydrology.max_river_centerlines",hydrology.max_river_centerlines) SETD("hydrology.delta_wave_reworking_strength",hydrology.delta_wave_reworking_strength) SETD("hydrology.delta_tide_reworking_strength",hydrology.delta_tide_reworking_strength) SETD("hydrology.delta_shelf_slope_scale",hydrology.delta_shelf_slope_scale) SETD("hydrology.delta_distributary_texture_strength",hydrology.delta_distributary_texture_strength)
 SETI("simulation.earth_system_passes",simulation.earth_system_passes) SETI("simulation.final_climate_ocean_passes",simulation.final_climate_ocean_passes) SETD("simulation.intermediate_climate_fraction",simulation.intermediate_climate_fraction) SETD("simulation.intermediate_ocean_fraction",simulation.intermediate_ocean_fraction) SETB("simulation.preserve_initial_sea_level",simulation.preserve_initial_sea_level) SETB("simulation.adaptive_convergence",simulation.adaptive_convergence) SETI("simulation.min_earth_system_passes",simulation.min_earth_system_passes) SETI("simulation.max_earth_system_passes",simulation.max_earth_system_passes) SETD("simulation.convergence_temperature_c",simulation.convergence_temperature_c) SETD("simulation.convergence_precip_mm_year",simulation.convergence_precip_mm_year) SETD("simulation.convergence_elevation_m",simulation.convergence_elevation_m) SETI("simulation.required_consecutive_converged_passes",simulation.required_consecutive_converged_passes) SETB("simulation.adaptive_final_coupling",simulation.adaptive_final_coupling) SETI("simulation.min_final_climate_ocean_passes",simulation.min_final_climate_ocean_passes) SETI("simulation.max_final_climate_ocean_passes",simulation.max_final_climate_ocean_passes) SETD("simulation.final_convergence_temperature_c",simulation.final_convergence_temperature_c) SETD("simulation.final_convergence_precip_mm_year",simulation.final_convergence_precip_mm_year) SETI("simulation.required_consecutive_final_converged_passes",simulation.required_consecutive_final_converged_passes)
 SETD("weather.hurricane_sst_c",weather.hurricane_sst_c) SETD("weather.hurricane_lat_min_deg",weather.hurricane_lat_min_deg) SETD("weather.hurricane_lat_max_deg",weather.hurricane_lat_max_deg) SETI("weather.hurricane_seed_count",weather.hurricane_seed_count) SETI("weather.hurricane_max_steps",weather.hurricane_max_steps)
 SETD("resources.deposit_density",resources.deposit_density) SETI("resources.meteorite_expected_count",resources.meteorite_expected_count)
 SETB("society.enabled",society.enabled) SETI("society.settlement_count",society.settlement_count) SETI("society.history_years",society.history_years) SETI("society.history_step_years",society.history_step_years) SETB("society.portal_prefer_mountains",society.portal_prefer_mountains) SETD("society.portal_latitude_max_deg",society.portal_latitude_max_deg) SETD("society.agricultural_productivity_weight",society.agricultural_productivity_weight) SETD("society.river_navigation_bonus",society.river_navigation_bonus) SETD("society.coastal_trade_bonus",society.coastal_trade_bonus)
 SETD("appearance.vegetation_temp_mid_c",appearance.vegetation_temp_mid_c) SETD("appearance.vegetation_temp_scale_c",appearance.vegetation_temp_scale_c) SETD("appearance.forest_precip_mid_mm_year",appearance.forest_precip_mid_mm_year) SETD("appearance.forest_precip_scale_mm_year",appearance.forest_precip_scale_mm_year) SETD("appearance.alpine_bare_start_km",appearance.alpine_bare_start_km) SETD("appearance.alpine_bare_full_km",appearance.alpine_bare_full_km) SETD("appearance.snow_albedo",appearance.snow_albedo) SETD("appearance.vegetation_albedo",appearance.vegetation_albedo) SETD("appearance.desert_albedo",appearance.desert_albedo) SETD("appearance.ocean_albedo",appearance.ocean_albedo) SETD("appearance.turbidity_spread_sigma_px",appearance.turbidity_spread_sigma_px) SETD("appearance.turbidity_strength",appearance.turbidity_strength) SETD("appearance.hillshade_strength",appearance.hillshade_strength) SETD("appearance.cloud_smoothing_sigma_px",appearance.cloud_smoothing_sigma_px) SETD("appearance.cloud_max_optical_opacity",appearance.cloud_max_optical_opacity) SETD("appearance.cloud_humidity_mid",appearance.cloud_humidity_mid) SETD("appearance.cloud_precip_mid_mm_month",appearance.cloud_precip_mid_mm_month)
 SETB("output.save_npz",output.save_npz) SETB("output.save_png",output.save_png) SETB("output.save_json",output.save_json) SETB("output.save_report",output.save_report) SETB("output.compress_npz",output.compress_npz) SETI("output.map_dpi",output.map_dpi) SETI("output.rgb_dpi",output.rgb_dpi)
#undef SETI
#undef SETD
#undef SETB
#undef SETS
 throw std::invalid_argument("unknown config key: "+k);
}
WorldConfig WorldConfig::load_yaml(const std::filesystem::path&p){std::ifstream in(p);if(!in)throw std::runtime_error("cannot open config: "+p.string());WorldConfig c;std::vector<std::pair<int,std::string>>sections;std::string line;std::size_t lineno=0;while(std::getline(in,line)){++lineno;auto hash=line.find('#');if(hash!=std::string::npos)line.resize(hash);if(trim(line).empty())continue;int indent=0;while(indent<static_cast<int>(line.size())&&line[static_cast<std::size_t>(indent)]==' ')++indent;if(indent%2)throw std::runtime_error("odd YAML indentation at line "+std::to_string(lineno));std::string body=trim(line);auto colon=body.find(':');if(colon==std::string::npos)throw std::runtime_error("expected key:value at line "+std::to_string(lineno));std::string key=trim(body.substr(0,colon)),val=trim(body.substr(colon+1));while(!sections.empty()&&sections.back().first>=indent)sections.pop_back();std::string path;for(auto&s:sections){if(!path.empty())path+='.';path+=s.second;}if(!path.empty())path+='.';path+=key;if(val.empty()){sections.emplace_back(indent,key);continue;}try{c.apply_override(path+"="+val);}catch(const std::exception&e){throw std::runtime_error("config line "+std::to_string(lineno)+": "+e.what());}}c.validate();return c;}
} // namespace worldgen
