#include "worldgen/field_io.hpp"
#include <array>
#include <fstream>
#include <stdexcept>
namespace worldgen { namespace {
constexpr std::array<char,8> magic{'W','G','F','S','E','T','1','\0'};
template<class T> void put(std::ostream&o,const T&v){o.write(reinterpret_cast<const char*>(&v),sizeof(T));if(!o)throw std::runtime_error("field-set write failed");}
template<class T> T get(std::istream&i){T v{};i.read(reinterpret_cast<char*>(&v),sizeof(T));if(!i)throw std::runtime_error("truncated field-set file");return v;}
std::uint64_t fnv(std::uint64_t h,const void*p,std::size_t n)noexcept{const auto*b=static_cast<const unsigned char*>(p);for(std::size_t i=0;i<n;++i){h^=b[i];h*=1099511628211ULL;}return h;}
}
std::uint64_t field_set_signature(const FieldSet&f)noexcept{std::uint64_t h=1469598103934665603ULL;for(const auto&[name,r]:f){h=fnv(h,name.data(),name.size());const auto hh=r.height(),ww=r.width();h=fnv(h,&hh,sizeof(hh));h=fnv(h,&ww,sizeof(ww));h=fnv(h,r.data(),r.size()*sizeof(float));}return h;}
void save_field_set_atomic(const std::filesystem::path&p,const FieldSet&f,std::uint64_t signature){if(f.empty())throw std::invalid_argument("cannot save empty field set");std::filesystem::create_directories(p.parent_path().empty()?std::filesystem::path("."):p.parent_path());auto tmp=p;tmp += ".tmp";{std::ofstream o(tmp,std::ios::binary|std::ios::trunc);if(!o)throw std::runtime_error("cannot open field-set output");o.write(magic.data(),magic.size());put<std::uint32_t>(o,1);put<std::uint32_t>(o,static_cast<std::uint32_t>(f.size()));put<std::uint64_t>(o,signature);for(const auto&[name,r]:f){if(name.size()>65535)throw std::length_error("field name too long");put<std::uint16_t>(o,static_cast<std::uint16_t>(name.size()));o.write(name.data(),static_cast<std::streamsize>(name.size()));put<std::uint64_t>(o,static_cast<std::uint64_t>(r.height()));put<std::uint64_t>(o,static_cast<std::uint64_t>(r.width()));o.write(reinterpret_cast<const char*>(r.data()),static_cast<std::streamsize>(r.size()*sizeof(float)));if(!o)throw std::runtime_error("field-set write failed");}o.flush();if(!o)throw std::runtime_error("field-set flush failed");}std::error_code ec;std::filesystem::rename(tmp,p,ec);if(ec){std::filesystem::remove(p,ec);ec.clear();std::filesystem::rename(tmp,p,ec);if(ec)throw std::runtime_error("atomic field-set rename failed: "+ec.message());}}
FieldSet load_field_set(const std::filesystem::path&p,std::uint64_t*signature){std::ifstream i(p,std::ios::binary);if(!i)throw std::runtime_error("cannot open field-set input");std::array<char,8>m{};i.read(m.data(),m.size());if(m!=magic)throw std::runtime_error("invalid field-set magic");const auto version=get<std::uint32_t>(i);if(version!=1)throw std::runtime_error("unsupported field-set version");const auto count=get<std::uint32_t>(i);const auto sig=get<std::uint64_t>(i);if(signature)*signature=sig;if(count==0||count>4096)throw std::runtime_error("invalid field count");FieldSet out;for(std::uint32_t k=0;k<count;++k){const auto nl=get<std::uint16_t>(i);std::string name(nl,'\0');i.read(name.data(),static_cast<std::streamsize>(nl));const auto h=get<std::uint64_t>(i),w=get<std::uint64_t>(i);if(h==0||w==0||h>1000000||w>1000000)throw std::runtime_error("invalid field dimensions");RasterF r(static_cast<std::size_t>(h),static_cast<std::size_t>(w));i.read(reinterpret_cast<char*>(r.data()),static_cast<std::streamsize>(r.size()*sizeof(float)));if(!i)throw std::runtime_error("truncated field payload");if(!out.emplace(std::move(name),std::move(r)).second)throw std::runtime_error("duplicate field name");}return out;}
} // namespace worldgen
