#include "worldgen/noise.hpp"
#include "worldgen/topology.hpp"
#include <algorithm>
#include <cmath>
#include <numeric>
#include <vector>
namespace worldgen {
namespace {
void standardize(RasterF&a){double sum=0,c=0;for(float z:a.span()){double t=sum+z;c+=(std::abs(sum)>=std::abs(z))?(sum-t)+z:(static_cast<double>(z)-t)+sum;sum=t;}double mean=(sum+c)/static_cast<double>(a.size()),var=0;for(float z:a.span()){double d=z-mean;var+=d*d;}double sd=std::sqrt(var/static_cast<double>(a.size()));if(!(sd>1e-8)){a.fill(0);return;}for(float&z:a.span())z=static_cast<float>((z-mean)/sd);}
NoiseBlend normalized_blend(NoiseBlend b){b.value=std::max(0.,b.value);b.ridge=std::max(0.,b.ridge);b.billow=std::max(0.,b.billow);b.wave=std::max(0.,b.wave);double s=b.value+b.ridge+b.billow+b.wave;if(s<=1e-12)return {1,0,0,0};b.value/=s;b.ridge/=s;b.billow/=s;b.wave/=s;return b;}
RasterF wave_field(const SphereGrid&g,Rng&r,double sigma,int count){RasterF out(g.height(),g.width(),0);double cycles=std::max(1.,static_cast<double>(g.width())/std::max(7.5*sigma,4.));for(int k=0;k<std::max(2,count);++k){int kx=std::max(1,static_cast<int>(std::llround(cycles*r.uniform(.55,1.55))));double ky=r.uniform(-.85,.85)*kx*.55,phase=r.uniform(0,2*kPi),amp=r.uniform(.65,1.);for(std::size_t y=0;y<g.height();++y){double yr=(kPi/2)-(static_cast<double>(y)+.5)*kPi/static_cast<double>(g.height());for(std::size_t x=0;x<g.width();++x){double xr=-kPi+2*kPi*static_cast<double>(x)/static_cast<double>(g.width());out(y,x)+=static_cast<float>(amp*std::sin(kx*xr+ky*yr+phase));}}}standardize(out);return out;}
RasterF smooth_random(const SphereGrid&g,Rng&r,double sigma,double anis=1.3){RasterF raw(g.height(),g.width());for(float&z:raw.span())z=static_cast<float>(r.normal());SphericalRasterOps ops(g);auto out=ops.gaussian_filter(raw,std::max(.35,sigma),std::max(.35,sigma*anis));standardize(out);return out;}
float sample(const RasterF&a,double sy,double sx){auto y0=static_cast<std::int64_t>(std::floor(sy)),x0=static_cast<std::int64_t>(std::floor(sx));double fy=sy-y0,fx=sx-x0;auto p00=map_spherical_index(y0,x0,a.height(),a.width()),p01=map_spherical_index(y0,x0+1,a.height(),a.width()),p10=map_spherical_index(y0+1,x0,a.height(),a.width()),p11=map_spherical_index(y0+1,x0+1,a.height(),a.width());auto z=[&](CellIndex p){return static_cast<double>(a(static_cast<std::size_t>(p.y),static_cast<std::size_t>(p.x)));};return static_cast<float>(z(p00)*(1-fy)*(1-fx)+z(p01)*(1-fy)*fx+z(p10)*fy*(1-fx)+z(p11)*fy*fx);}
}
RasterF hybrid_multifractal(const SphereGrid&g,Rng&r,const NoiseConfig&cfg,NoiseBlend blend,int octaves_override,double base_scale_px,double clip){int oct=octaves_override>0?octaves_override:cfg.octaves;oct=std::clamp(oct,1,16);double persistence=std::clamp(cfg.persistence,.05,.95),lacunarity=std::max(cfg.lacunarity,1.15),base=base_scale_px>0?base_scale_px:std::max(static_cast<double>(g.height())/7.5,3.);blend=normalized_blend(blend);RasterF acc(g.height(),g.width(),0);double weights=0;
 for(int o=0;o<oct;++o){double sigma=std::max(cfg.minimum_sigma_px,base/std::pow(lacunarity,o));auto value=smooth_random(g,r,sigma);auto aux=smooth_random(g,r,std::max(cfg.minimum_sigma_px,sigma*.76),1.37);auto wave=wave_field(g,r,sigma,cfg.wave_count);RasterF octave(g.height(),g.width());for(std::size_t i=0;i<octave.size();++i){double v=value.span()[i],a=aux.span()[i],ridge=1-std::abs(v),billow=std::abs(a);octave.span()[i]=static_cast<float>(blend.value*v+blend.ridge*ridge+blend.billow*billow+blend.wave*wave.span()[i]);}standardize(octave);double amp=std::pow(persistence,o);for(std::size_t i=0;i<acc.size();++i)acc.span()[i]+=static_cast<float>(amp*octave.span()[i]);weights+=amp;}
 for(float&z:acc.span())z=static_cast<float>(z/weights);
 if(cfg.domain_warp_strength>1e-5){auto wy=smooth_random(g,r,std::max(2.,base*1.35),1.25),wx=smooth_random(g,r,std::max(2.,base*1.16),1.3);double warp=std::min(base*cfg.domain_warp_strength,.09*static_cast<double>(std::min(g.height(),g.width())));RasterF src=acc;for(std::size_t y=0;y<g.height();++y){double taper=std::clamp(std::cos(g.lat(y)*kDegToRad),.18,1.);for(std::size_t x=0;x<g.width();++x)acc(y,x)=sample(src,static_cast<double>(y)+wy(y,x)*warp,static_cast<double>(x)+wx(y,x)*warp*taper);}}
 standardize(acc);if(clip>0){for(float&z:acc.span())z=static_cast<float>(std::clamp(static_cast<double>(z),-clip,clip));standardize(acc);}return acc;}
RasterF hybrid_noise01(const SphereGrid&g,Rng&r,const NoiseConfig&c,NoiseBlend b,int o,double base){auto z=hybrid_multifractal(g,r,c,b,o,base);for(float&v:z.span())v=static_cast<float>(.5+.5*std::tanh(.72*v));return z;}
StaticNoiseFields build_static_noise_fields(const SphereGrid&g,const NoiseConfig&c,const RngPool&p){auto r1=p("noise:ocean");auto r2=p("noise:climate");auto r3=p("noise:convection");auto r4=p("noise:geology-lith");auto r5=p("noise:geology-igneous");auto r6=p("noise:hydro-wiggle");auto r7=p("noise:delta-texture");return {hybrid_multifractal(g,r1,c,kOceanBlend,std::clamp(c.octaves,5,8),std::max(static_cast<double>(g.height())/32.,2.5)),hybrid_multifractal(g,r2,c,kClimateBlend,std::clamp(c.octaves,4,7),std::max(static_cast<double>(g.height())/16.,4.)),hybrid_noise01(g,r3,c,{.48,.07,.27,.18},std::clamp(c.octaves,4,6),std::max(static_cast<double>(g.height())/20.,3.)),hybrid_noise01(g,r4,c,kGeologyBlend,std::clamp(c.octaves,5,8),std::max(static_cast<double>(g.height())/22.,3.)),hybrid_noise01(g,r5,c,{.34,.28,.12,.26},std::clamp(c.octaves,4,7),std::max(static_cast<double>(g.height())/30.,2.5)),hybrid_multifractal(g,r6,c,kHydroBlend,std::clamp(c.octaves,5,8),std::max(static_cast<double>(g.height())/36.,2.5)),hybrid_noise01(g,r7,c,{.36,.25,.12,.27},std::clamp(c.octaves,4,7),std::max(static_cast<double>(g.height())/50.,2.))};}
} // namespace worldgen
