#include "worldgen/planetary_physics.hpp"
#include "worldgen/common.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>
namespace worldgen { namespace {
constexpr double kG=6.67430e-11,kEarthMassKg=5.9722e24;
double cell_area_m2(const SphereGrid&g,std::size_t y){const double r=g.radius_km()*1000.0;return 4.0*kPi*r*r*g.area_weight(y);}
double tidal_power(double host_kg,double radius_m,double a_m,double e,double k2,double q){if(!(host_kg>0&&radius_m>0&&a_m>0&&q>0))return 0;const double n=std::sqrt(kG*host_kg/(a_m*a_m*a_m));return 10.5*(k2/q)*kG*host_kg*host_kg*std::pow(radius_m,5)*n*e*e/std::pow(a_m,6);}
double clamp01(double x){return std::clamp(x,0.0,1.0);}
struct Cell{double z,area;};
SurfaceLiquidResult fill_liquid(const SphereGrid&grid,const RasterF&elev,double volume,double density,const std::map<std::string,double>&mix){if(elev.height()!=grid.height()||elev.width()!=grid.width())throw std::invalid_argument("elevation/grid mismatch");SurfaceLiquidResult r;r.depth_m=RasterF(elev.height(),elev.width(),0.0f);r.volume_m3=std::max(0.0,volume);r.effective_density_kg_m3=density;r.mass_kg=r.volume_m3*density;r.liquid_mass_fraction=mix;if(volume<=0){r.level_km=static_cast<double>(*std::min_element(elev.span().begin(),elev.span().end()));return r;}std::vector<Cell>cells;cells.reserve(elev.size());for(std::size_t y=0;y<elev.height();++y){const double a=cell_area_m2(grid,y);for(std::size_t x=0;x<elev.width();++x)cells.push_back({static_cast<double>(elev(y,x))*1000.0,a});}std::sort(cells.begin(),cells.end(),[](const auto&lhs,const auto&rhs){return lhs.z<rhs.z;});double remaining=volume,level=cells.front().z,active=0;std::size_t i=0;while(i<cells.size()){const double z=cells[i].z;if(active>0&&z>level){const double need=active*(z-level);if(remaining<need){level+=remaining/active;remaining=0;break;}remaining-=need;level=z;}while(i<cells.size()&&cells[i].z==z){active+=cells[i].area;++i;}}if(remaining>0&&active>0)level+=remaining/active;r.level_km=level/1000.0;for(std::size_t y=0;y<elev.height();++y)for(std::size_t x=0;x<elev.width();++x)r.depth_m(y,x)=static_cast<float>(std::max(0.0,level-static_cast<double>(elev(y,x))*1000.0));return r;}
}
TidalHeatingResult tidal_heating(const WorldOrbit&o,double world_mass_earth,double world_radius_km){(void)world_mass_earth;TidalHeatingResult r;if(o.is_moon&&o.host_mass_earth>0&&o.host_semimajor_axis_km>0){r.host_tidal_power_w=tidal_power(o.host_mass_earth*kEarthMassKg,world_radius_km*1000.0,o.host_semimajor_axis_km*1000.0,o.host_eccentricity,o.world_k2,o.world_quality_factor);r.host_surface_flux_w_m2=r.host_tidal_power_w/(4*kPi*std::pow(world_radius_km*1000.0,2));}double sum=0;for(const auto&m:o.moons){if(m.mass_earth<=0||m.semimajor_axis_km<=0)continue;const double index=m.mass_earth/std::pow(m.semimajor_axis_km/384400.0,3);r.moon_relative_tidal_forcing[m.name]=index/0.0123;sum+=std::abs(index);}r.satellite_tidal_forcing_index=sum;r.host_surface_flux_w_m2=std::max(0.0,r.host_surface_flux_w_m2);return r;}
VolatileCycleResult solve_volatile_cycle(const ChemicalDatabase&db,const SphereGrid&grid,const RasterF&elev,const RasterF&temp,double pressure,double gravity,const std::vector<VolatileInventory>&inv,double ice_eff){if(elev.height()!=grid.height()||elev.width()!=grid.width()||temp.height()!=grid.height()||temp.width()!=grid.width())throw std::invalid_argument("volatile-cycle grid mismatch");if(!(gravity>0))throw std::invalid_argument("gravity must be positive");VolatileCycleResult out;double total_liq_mass=0,total_liq_vol=0;std::map<std::string,double>liq_mass;double dominant=0;for(const auto&v:inv){const auto*s=db.find(v.formula);if(!s||v.total_mass_kg<=0)continue;double gas_cap=0,ice_w=0,liq_w=0;for(std::size_t y=0;y<grid.height();++y){const double area=cell_area_m2(grid,y),aw=grid.area_weight(y);for(std::size_t x=0;x<grid.width();++x){const double t=temp(y,x);const double ps=std::min(saturation_vapor_pressure_pa(*s,t),pressure);gas_cap+=ps*area/gravity;const auto ph=phase_at(*s,t,pressure);if(ph==Phase::solid)ice_w+=aw;else if(ph==Phase::liquid)liq_w+=aw;}}const double gas=std::min(v.total_mass_kg,gas_cap),condensed=std::max(0.0,v.total_mass_kg-gas);const double cold=std::max(0.0,ice_w)*std::clamp(ice_eff,0.0,1.0),warm=std::max(0.0,liq_w);const double ice_frac=(cold+warm>0)?cold/(cold+warm):1.0;const double ice=condensed*ice_frac,liquid=condensed-ice;double tliq=0,tw=0;for(std::size_t y=0;y<grid.height();++y)for(std::size_t x=0;x<grid.width();++x)if(phase_at(*s,temp(y,x),pressure)==Phase::liquid){tliq+=static_cast<double>(temp(y,x))*grid.area_weight(y);tw+=grid.area_weight(y);}const double mean_liq_t=tw>0?tliq/tw:s->boiling_temperature_k;const double rho=liquid_density_kg_m3(*s,mean_liq_t);out.species.push_back({v.formula,gas,ice,liquid,rho,gas_cap,liq_w,ice_w});if(liquid>0){const double vol=liquid/rho;total_liq_mass+=liquid;total_liq_vol+=vol;liq_mass[v.formula]=liquid;if(liquid>dominant){dominant=liquid;out.dominant_surface_liquid=v.formula;}}if(gas>0&&condensed>0)out.precipitating_species.push_back(v.formula);}
std::map<std::string,double>mix;for(const auto&[f,mass]:liq_mass)mix[f]=mass/std::max(total_liq_mass,1e-30);const double rho_eff=total_liq_vol>0?total_liq_mass/total_liq_vol:1000;out.surface_liquid=fill_liquid(grid,elev,total_liq_vol,rho_eff,mix);if(!out.dominant_surface_liquid.empty()){if(const auto*s=db.find(out.dominant_surface_liquid)){const double density_factor=std::pow(std::max(s->liquid_density_kg_m3,1.0)/997.0,0.65);const double viscosity_factor=std::pow(0.89/std::max(s->liquid_viscosity_mpa_s,0.01),0.16);const double tension_factor=std::pow(std::max(s->surface_tension_mn_m,0.5)/72.0,0.10);out.geomorphic_stream_power_factor=std::clamp(density_factor*viscosity_factor*tension_factor,0.25,2.5);out.sediment_transport_factor=std::clamp(std::sqrt(density_factor)*std::pow(viscosity_factor,0.7),0.3,3.0);}}return out;}
std::string_view geodynamic_regime_name(GeodynamicRegime r)noexcept{switch(r){case GeodynamicRegime::silicate_mobile_lid:return"silicate_mobile_lid";case GeodynamicRegime::silicate_stagnant_lid:return"silicate_stagnant_lid";case GeodynamicRegime::heat_pipe:return"heat_pipe";case GeodynamicRegime::cryotectonic:return"cryotectonic";case GeodynamicRegime::mixed_silicate_cryo:return"mixed_silicate_cryo";default:return"frozen_inactive";}}
GeodynamicResult classify_geodynamics(double mass,double radius,double age,double ts,double tide,const VolatileCycleResult&v){GeodynamicResult r;const double radiogenic=0.085*std::pow(std::max(mass,0.05),0.72)/std::pow(std::max(radius,0.2),2)*std::exp(-std::max(age,0.0)/5.5);r.internal_heat_flux_w_m2=std::max(0.0,radiogenic+tide);r.tidal_fraction=r.internal_heat_flux_w_m2>0?std::clamp(tide/r.internal_heat_flux_w_m2,0.0,1.0):0;bool icy=false;for(const auto&p:v.species)if((p.formula=="H2O"||p.formula=="NH3"||p.formula=="CH4"||p.formula=="N2")&&p.ice_mass_kg>1e15)icy=true;const double q=std::max(r.internal_heat_flux_w_m2,1e-5);r.estimated_ice_shell_km=icy?std::clamp(2.5*std::max(273.15-ts,0.0)/q/1000.0,0.0,5000.0):0;r.cryovolcanism_index=icy?clamp01((q-0.015)/0.12)*clamp01((260.0-ts)/120.0+0.25):0;if(icy){r.plausible_cryomelts.push_back("H2O");for(const auto&p:v.species)if(p.formula=="NH3"&&p.ice_mass_kg>0)r.plausible_cryomelts.push_back("H2O-NH3");if(v.dominant_surface_liquid=="CH4"||v.dominant_surface_liquid=="C2H6")r.plausible_cryomelts.push_back("hydrocarbon-rich near-surface reservoirs");}const bool silicate_active=q>0.065*std::pow(std::max(radius,0.4),0.25),very_hot=q>0.35;if(very_hot)r.regime=GeodynamicRegime::heat_pipe;else if(silicate_active&&icy&&r.cryovolcanism_index>0.2)r.regime=GeodynamicRegime::mixed_silicate_cryo;else if(silicate_active)r.regime=GeodynamicRegime::silicate_mobile_lid;else if(icy&&r.cryovolcanism_index>0.12)r.regime=GeodynamicRegime::cryotectonic;else if(q>0.012)r.regime=GeodynamicRegime::silicate_stagnant_lid;else r.regime=GeodynamicRegime::frozen_inactive;return r;}
} // namespace worldgen
