#include "worldgen/profile.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <fstream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <vector>
namespace worldgen { namespace {
std::string trim(std::string s){auto ns=[](unsigned char c){return !std::isspace(c);};s.erase(s.begin(),std::find_if(s.begin(),s.end(),ns));s.erase(std::find_if(s.rbegin(),s.rend(),ns).base(),s.end());if(s.size()>=2&&((s.front()=='"'&&s.back()=='"')||(s.front()=='\''&&s.back()=='\'')))s=s.substr(1,s.size()-2);return s;}
double num(const std::string&s){std::size_t p=0;double v=std::stod(s,&p);if(p!=s.size()||!std::isfinite(v))throw std::invalid_argument("invalid numeric profile value: "+s);return v;}
std::size_t usize(const std::string&s){std::size_t p=0;const auto v=std::stoull(s,&p);if(p!=s.size()||v>std::numeric_limits<std::size_t>::max())throw std::invalid_argument("invalid integer profile value: "+s);return static_cast<std::size_t>(v);}
bool boolean(const std::string&s){if(s=="true"||s=="True")return true;if(s=="false"||s=="False")return false;throw std::invalid_argument("invalid boolean profile value: "+s);}
std::vector<std::string> split(const std::string&s,char d){std::vector<std::string>v;std::stringstream ss(s);std::string p;while(std::getline(ss,p,d))v.push_back(p);return v;}
void assign(PlanetProfile&p,std::map<std::string,SatelliteOrbit>&moons,const std::string&k,const std::string&v){
 if(k=="seed"){p.seed=static_cast<std::uint64_t>(std::stoull(v));return;}if(k=="resolution.width"){p.width=usize(v);return;}if(k=="resolution.height"){p.height=usize(v);return;}
 if(k=="star.mass_solar"){p.star_mass_solar=num(v);return;}if(k=="star.luminosity_solar"){p.star_luminosity_solar=num(v);return;}if(k=="star.uv_relative_earth"){p.star_uv_relative_earth=num(v);return;}
 if(k=="world.mass_earth"){p.world_mass_earth=num(v);return;}if(k=="world.radius_earth"){p.world_radius_earth=num(v);return;}if(k=="world.age_gyr"){p.world_age_gyr=num(v);return;}if(k=="world.orbital_distance_au"){p.orbital_distance_au=num(v);return;}if(k=="world.rotation_hours"){p.rotation_hours=num(v);return;}if(k=="world.axial_tilt_deg"){p.axial_tilt_deg=num(v);return;}if(k=="world.bond_albedo"){p.bond_albedo=num(v);return;}if(k=="world.gravity_override_m_s2"){p.gravity_override_m_s2=num(v);return;}
 if(k=="atmosphere.surface_pressure_pa"){p.atmosphere.surface_pressure_pa=num(v);return;}if(k.rfind("atmosphere.composition.",0)==0){p.atmosphere.mole_fraction[k.substr(23)]=num(v);return;}
 if(k.rfind("volatiles.",0)==0){const auto f=k.substr(10);p.volatiles[f]={f,num(v)};return;}
 if(k=="orbit.is_moon"){p.orbit.is_moon=boolean(v);return;}if(k=="orbit.host_mass_earth"){p.orbit.host_mass_earth=num(v);return;}if(k=="orbit.host_radius_km"){p.orbit.host_radius_km=num(v);return;}if(k=="orbit.host_semimajor_axis_km"){p.orbit.host_semimajor_axis_km=num(v);return;}if(k=="orbit.host_eccentricity"){p.orbit.host_eccentricity=num(v);return;}if(k=="orbit.world_k2"){p.orbit.world_k2=num(v);return;}if(k=="orbit.world_quality_factor"){p.orbit.world_quality_factor=num(v);return;}
 if(k.rfind("moons.",0)==0){const auto parts=split(k,'.');if(parts.size()!=3)throw std::invalid_argument("moon property must be moons.NAME.FIELD");auto&m=moons[parts[1]];m.name=parts[1];const auto&f=parts[2];if(f=="mass_earth")m.mass_earth=num(v);else if(f=="radius_km")m.radius_km=num(v);else if(f=="semimajor_axis_km")m.semimajor_axis_km=num(v);else if(f=="eccentricity")m.eccentricity=num(v);else if(f=="k2")m.k2=num(v);else if(f=="quality_factor")m.quality_factor=num(v);else throw std::invalid_argument("unknown moon property: "+f);return;}
 if(k=="geology.regime"){p.geology_regime=v;return;}if(k=="geology.relief_scale"){p.relief_scale=num(v);return;}if(k=="volatile_cycle.ice_trapping_efficiency"){p.ice_trapping_efficiency=num(v);return;}if(k=="geomorphology.erosion_iterations"){p.erosion_iterations=static_cast<int>(usize(v));return;}
 if(k=="refinement.levels"){p.refinement.levels=usize(v);return;}if(k=="refinement.scale"){p.refinement.scale=usize(v);return;}if(k=="refinement.tiles_y"){p.refinement.tiles_y=usize(v);return;}if(k=="refinement.tiles_x"){p.refinement.tiles_x=usize(v);return;}if(k=="refinement.halo"){p.refinement.halo=usize(v);return;}if(k=="refinement.resume"){p.refinement.resume=boolean(v);return;}if(k=="refinement.checkpoint"){p.refinement.checkpoint=boolean(v);return;}if(k=="refinement.checkpoint_dir"){p.refinement.checkpoint_dir=v;return;}
 if(k=="noise.octaves"){p.noise.octaves=static_cast<int>(usize(v));return;}if(k=="noise.persistence"){p.noise.persistence=num(v);return;}if(k=="noise.lacunarity"){p.noise.lacunarity=num(v);return;}if(k=="noise.domain_warp_strength"){p.noise.domain_warp_strength=num(v);return;}
 throw std::invalid_argument("unknown profile key: "+k);
}
}
double PlanetProfile::gravity_m_s2()const noexcept{return gravity_override_m_s2>0?gravity_override_m_s2:9.80665*world_mass_earth/(world_radius_earth*world_radius_earth);}
PlanetProfile PlanetProfile::earthlike(){PlanetProfile p;p.atmosphere.mole_fraction={{"N2",0.7808},{"O2",0.2095},{"Ar",0.0093},{"CO2",0.00042},{"H2O",0.0}};p.volatiles.emplace("H2O",VolatileInventory{"H2O",1.4e21});p.orbit.star_mass_solar=p.star_mass_solar;p.orbit.star_luminosity_solar=p.star_luminosity_solar;p.orbit.stellar_distance_au=p.orbital_distance_au;return p;}
void PlanetProfile::validate()const{if(width<64||height<32||width!=2*height)throw std::invalid_argument("profile resolution must be a >=64x32 2:1 sphere");if(!(star_mass_solar>0&&star_luminosity_solar>0&&world_mass_earth>0&&world_radius_earth>0&&orbital_distance_au>0&&rotation_hours>0))throw std::invalid_argument("profile physical parameters must be positive");if(!(bond_albedo>=0&&bond_albedo<1))throw std::invalid_argument("bond albedo must be in [0,1)");if(!(atmosphere.surface_pressure_pa>0))throw std::invalid_argument("surface pressure must be positive");double sum=0;for(const auto&[f,x]:atmosphere.mole_fraction){if(f.empty()||x<0||!std::isfinite(x))throw std::invalid_argument("invalid atmosphere component");sum+=x;}if(!(sum>0))throw std::invalid_argument("atmosphere composition must have positive sum");if(orbit.is_moon&&!(orbit.host_mass_earth>0&&orbit.host_semimajor_axis_km>0))throw std::invalid_argument("moon worlds require host mass and orbital radius");if(erosion_iterations<0||erosion_iterations>128)throw std::invalid_argument("erosion iteration count out of range");if(!(ice_trapping_efficiency>=0&&ice_trapping_efficiency<=1))throw std::invalid_argument("ice trapping efficiency out of range");if(geology_regime!="auto"&&geology_regime!="active"&&geology_regime!="inactive"&&geology_regime!="cryogenic"&&geology_regime!="mixed")throw std::invalid_argument("unknown geology regime");}
PlanetProfile PlanetProfile::load_yaml(const std::filesystem::path&path){std::ifstream in(path);if(!in)throw std::runtime_error("cannot open planet profile: "+path.string());PlanetProfile p=earthlike();p.atmosphere.mole_fraction.clear();p.volatiles.clear();std::map<std::string,SatelliteOrbit>moons;struct Level{int indent;std::string key;};std::vector<Level>stack;std::string line;std::size_t lineno=0;while(std::getline(in,line)){++lineno;const auto hash=line.find('#');if(hash!=std::string::npos)line.erase(hash);if(trim(line).empty())continue;int indent=0;while(indent<static_cast<int>(line.size())&&line[static_cast<std::size_t>(indent)]==' ')++indent;const auto body=trim(line);const auto colon=body.find(':');if(colon==std::string::npos)throw std::invalid_argument("profile YAML missing ':' at line "+std::to_string(lineno));const auto key=trim(body.substr(0,colon)),value=trim(body.substr(colon+1));while(!stack.empty()&&indent<=stack.back().indent)stack.pop_back();std::string full;for(const auto&s:stack){if(!full.empty())full+='.';full+=s.key;}if(!full.empty())full+='.';full+=key;if(value.empty()){stack.push_back({indent,key});continue;}assign(p,moons,full,value);}p.orbit.moons.clear();for(auto&[name,m]:moons){(void)name;p.orbit.moons.push_back(std::move(m));}p.orbit.star_mass_solar=p.star_mass_solar;p.orbit.star_luminosity_solar=p.star_luminosity_solar;p.orbit.stellar_distance_au=p.orbital_distance_au;p.validate();return p;}
} // namespace worldgen
