#include "worldgen/progress.hpp"
#include <algorithm>
#include <cmath>
#include <iomanip>
#include <iostream>
#include <sstream>
namespace worldgen {
ProgressTracker::ProgressTracker(ProgressOptions options,std::ostream* stream):options_(options),stream_(stream?stream:&std::cerr){}
std::size_t ProgressTracker::depth_of(const std::string&p){return static_cast<std::size_t>(std::count(p.begin(),p.end(),'/'));}
void ProgressTracker::begin(const std::string&path,std::uint64_t total,const std::string&description){std::scoped_lock lock(mutex_);auto&n=nodes_[path];n.total=total;n.done=0;n.start=n.last=Clock::now();n.ema_rate=0;n.description=description;n.detail.clear();n.finished=false;if(options_.verbose)emit_locked(path,n,true);}
void ProgressTracker::update(const std::string&path,std::uint64_t completed,const std::string&detail){std::scoped_lock lock(mutex_);auto it=nodes_.find(path);if(it==nodes_.end())return;auto&n=it->second;const auto now=Clock::now();const double dt=std::chrono::duration<double>(now-n.last).count();const auto old=n.done;n.done=std::min(completed,n.total);if(dt>1e-6&&n.done>old){const double rate=static_cast<double>(n.done-old)/dt;n.ema_rate=n.ema_rate<=0?rate:0.22*rate+0.78*n.ema_rate;}n.last=now;n.detail=detail;emit_locked(path,n,false);}
void ProgressTracker::advance(const std::string&path,std::uint64_t delta,const std::string&detail){std::scoped_lock lock(mutex_);auto it=nodes_.find(path);if(it==nodes_.end())return;auto&n=it->second;const auto now=Clock::now();const double dt=std::chrono::duration<double>(now-n.last).count();const auto old=n.done;n.done=std::min(n.total,n.done+delta);if(dt>1e-6&&n.done>old){const double rate=static_cast<double>(n.done-old)/dt;n.ema_rate=n.ema_rate<=0?rate:0.22*rate+0.78*n.ema_rate;}n.last=now;n.detail=detail;emit_locked(path,n,false);}
void ProgressTracker::finish(const std::string&path,const std::string&detail){std::scoped_lock lock(mutex_);auto it=nodes_.find(path);if(it==nodes_.end())return;auto&n=it->second;n.done=n.total;n.detail=detail;n.finished=true;n.last=Clock::now();emit_locked(path,n,true);}
void ProgressTracker::message(const std::string&path,const std::string&text){if(!options_.verbose)return;std::scoped_lock lock(mutex_);(*stream_)<<std::string(depth_of(path)*2,' ')<<"["<<path<<"] "<<text<<'\n';}
std::optional<double> ProgressTracker::eta_seconds(const std::string&path)const{std::scoped_lock lock(mutex_);auto it=nodes_.find(path);if(it==nodes_.end())return std::nullopt;const auto&n=it->second;if(n.done>=n.total)return 0.0;double rate=n.ema_rate;if(!(rate>0)){const double e=std::chrono::duration<double>(Clock::now()-n.start).count();if(e>0&&n.done>0)rate=static_cast<double>(n.done)/e;}if(!(rate>0))return std::nullopt;return static_cast<double>(n.total-n.done)/rate;}
void ProgressTracker::emit_locked(const std::string&path,const Node&n,bool force){if(!options_.enabled)return;if(!options_.progress_bar&&!options_.verbose&&!force)return;const double frac=n.total?static_cast<double>(n.done)/static_cast<double>(n.total):1.0;const double elapsed=std::chrono::duration<double>(Clock::now()-n.start).count();double rate=n.ema_rate;if(!(rate>0)&&elapsed>0&&n.done>0)rate=static_cast<double>(n.done)/elapsed;std::ostringstream ss;ss<<std::string(depth_of(path)*2,' ')<<'['<<path<<"] ";if(options_.progress_bar){const auto filled=static_cast<std::size_t>(std::llround(frac*static_cast<double>(options_.bar_width)));const auto capped=std::min(filled,options_.bar_width);ss<<'['<<std::string(capped,'=')<<std::string(options_.bar_width-capped,' ')<<"] ";}ss<<std::fixed<<std::setprecision(1)<<100.0*frac<<"% "<<n.done<<'/'<<n.total<<" elapsed="<<elapsed<<'s';if(rate>0&&n.done<n.total)ss<<" eta="<<static_cast<double>(n.total-n.done)/rate<<'s';if(!n.description.empty())ss<<" "<<n.description;if(!n.detail.empty())ss<<" :: "<<n.detail;(*stream_)<<ss.str()<<'\n';}
} // namespace worldgen
