#include "worldgen/refinement.hpp"
#include "worldgen/common.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <sstream>
#include <stdexcept>
namespace worldgen { namespace {
struct Index{std::int64_t y,x;};
Index map_sphere(std::int64_t y,std::int64_t x,std::int64_t h,std::int64_t w){if(h<=0||w<=0)throw std::invalid_argument("invalid spherical shape");while(y<0||y>=h){if(y<0){y=-y-1;x+=w/2;}if(y>=h){y=2*h-y-1;x+=w/2;}}x%=w;if(x<0)x+=w;return {y,x};}
float sample_spherical(const RasterF&a,double sy,double sx){const auto h=static_cast<std::int64_t>(a.height()),w=static_cast<std::int64_t>(a.width());const auto y0=static_cast<std::int64_t>(std::floor(sy)),x0=static_cast<std::int64_t>(std::floor(sx));const double fy=sy-static_cast<double>(y0),fx=sx-static_cast<double>(x0);const auto p00=map_sphere(y0,x0,h,w),p01=map_sphere(y0,x0+1,h,w),p10=map_sphere(y0+1,x0,h,w),p11=map_sphere(y0+1,x0+1,h,w);return static_cast<float>((1-fy)*((1-fx)*a(static_cast<std::size_t>(p00.y),static_cast<std::size_t>(p00.x))+fx*a(static_cast<std::size_t>(p01.y),static_cast<std::size_t>(p01.x)))+fy*((1-fx)*a(static_cast<std::size_t>(p10.y),static_cast<std::size_t>(p10.x))+fx*a(static_cast<std::size_t>(p11.y),static_cast<std::size_t>(p11.x))));}
std::pair<std::size_t,std::size_t> bounds(std::size_t i,std::size_t n,std::size_t total){return {i*total/n,(i+1)*total/n};}
double taper_axis(std::int64_t p,std::int64_t c0,std::int64_t c1,std::size_t halo){if(p>=c0&&p<c1)return 1.0;if(halo==0)return 0.0;double d=0;if(p<c0)d=static_cast<double>(c0-p);else d=static_cast<double>(p-(c1-1));const double t=std::clamp(1.0-d/(static_cast<double>(halo)+1.0),0.0,1.0);return 0.5-0.5*std::cos(kPi*t);}
std::string address(std::size_t level,std::size_t ty,std::size_t tx,std::size_t by,std::size_t bx){std::vector<std::pair<std::size_t,std::size_t>>digits;for(std::size_t d=0;d<level;++d){digits.push_back({ty%by,tx%bx});ty/=by;tx/=bx;}std::ostringstream s;s<<"L"<<level;for(auto it=digits.rbegin();it!=digits.rend();++it)s<<"/y"<<it->first<<"x"<<it->second;return s.str();}
std::uint64_t mix64(std::uint64_t h,std::uint64_t v)noexcept{h^=v+0x9e3779b97f4a7c15ULL+(h<<6)+(h>>2);return h;}
std::uint64_t text_hash(std::string_view s)noexcept{std::uint64_t h=1469598103934665603ULL;for(unsigned char c:s){h^=c;h*=1099511628211ULL;}return h;}
std::uint64_t tile_signature(const FieldSet&patch,const RefinementContext&c,std::string_view kernel){auto h=field_set_signature(patch);h=mix64(h,c.level);h=mix64(h,c.tile_y);h=mix64(h,c.tile_x);h=mix64(h,c.scale);h=mix64(h,c.halo);h=mix64(h,text_hash(kernel));return h;}
std::size_t ipow(std::size_t b,std::size_t e){std::size_t r=1;for(std::size_t i=0;i<e;++i){if(b!=0&&r>std::numeric_limits<std::size_t>::max()/b)throw std::overflow_error("refinement tile count overflow");r*=b;}return r;}
void validate_shapes(const FieldSet&f){if(f.empty())throw std::invalid_argument("refinement requires at least one field");const auto h=f.begin()->second.height(),w=f.begin()->second.width();for(const auto&[name,r]:f){(void)name;if(r.height()!=h||r.width()!=w)throw std::invalid_argument("all refined fields must share one grid shape");}}
}
RecursiveRefiner::RecursiveRefiner(RefinementOptions o):options_(std::move(o)){if(options_.levels>8)throw std::invalid_argument("refinement levels capped at 8 per invocation");if(options_.scale<2||options_.scale>8)throw std::invalid_argument("refinement scale must be 2..8");if(options_.tiles_y<1||options_.tiles_x<1)throw std::invalid_argument("tile counts must be positive");if(options_.halo>4096)throw std::invalid_argument("halo too large");if(options_.kernel_fingerprint.empty())throw std::invalid_argument("kernel fingerprint must not be empty");}
RefinementResult RecursiveRefiner::run(const FieldSet&base,const RefineKernel&kernel,ProgressTracker*progress)const{validate_shapes(base);FieldSet current=base;RefinementResult result;for(std::size_t level=1;level<=options_.levels;++level){validate_shapes(current);const auto in_h=current.begin()->second.height(),in_w=current.begin()->second.width();if(in_h>std::numeric_limits<std::size_t>::max()/options_.scale||in_w>std::numeric_limits<std::size_t>::max()/options_.scale)throw std::overflow_error("refined resolution overflow");const auto out_h=in_h*options_.scale,out_w=in_w*options_.scale;const auto rows=ipow(options_.tiles_y,level),cols=ipow(options_.tiles_x,level);if(rows>out_h||cols>out_w)throw std::invalid_argument("recursive tile grid exceeds output resolution");const auto tile_total=checked_mul(rows,cols);const std::string level_path="refine/L"+std::to_string(level);if(progress)progress->begin(level_path,static_cast<std::uint64_t>(tile_total),"recursive spherical refinement");std::map<std::string,RasterD>sums,weights;for(const auto&[name,r]:current){(void)r;sums.emplace(name,RasterD(out_h,out_w,0.0));weights.emplace(name,RasterD(out_h,out_w,0.0));}
for(std::size_t ty=0;ty<rows;++ty){for(std::size_t tx=0;tx<cols;++tx){const auto[y0u,y1u]=bounds(ty,rows,out_h);const auto[x0u,x1u]=bounds(tx,cols,out_w);const auto y0=static_cast<std::int64_t>(y0u),y1=static_cast<std::int64_t>(y1u),x0=static_cast<std::int64_t>(x0u),x1=static_cast<std::int64_t>(x1u);const auto halo=static_cast<std::int64_t>(options_.halo);const auto eh=static_cast<std::size_t>((y1-y0)+2*halo),ew=static_cast<std::size_t>((x1-x0)+2*halo);FieldSet patch;for(const auto&[name,src]:current){RasterF p(eh,ew);for(std::size_t py=0;py<eh;++py){const auto gy=y0-halo+static_cast<std::int64_t>(py);const double sy=(static_cast<double>(gy)+0.5)/static_cast<double>(options_.scale)-0.5;for(std::size_t px=0;px<ew;++px){const auto gx=x0-halo+static_cast<std::int64_t>(px);const double sx=(static_cast<double>(gx)+0.5)/static_cast<double>(options_.scale)-0.5;p(py,px)=sample_spherical(src,sy,sx);}}patch.emplace(name,std::move(p));}
RefinementContext ctx;ctx.level=level;ctx.tile_y=ty;ctx.tile_x=tx;ctx.tile_rows=rows;ctx.tile_cols=cols;ctx.scale=options_.scale;ctx.halo=options_.halo;ctx.global_y0=y0;ctx.global_x0=x0;ctx.core_height=y1u-y0u;ctx.core_width=x1u-x0u;ctx.cumulative_scale=std::pow(static_cast<double>(options_.scale),static_cast<double>(level));ctx.path=address(level,ty,tx,options_.tiles_y,options_.tiles_x);const auto sig=tile_signature(patch,ctx,options_.kernel_fingerprint);bool resumed=false;std::filesystem::path cp;if(options_.checkpoint){cp=options_.checkpoint_dir/(ctx.path+".wgfs");if(options_.resume&&std::filesystem::exists(cp)){try{std::uint64_t stored=0;auto loaded=load_field_set(cp,&stored);if(stored==sig){validate_shapes(loaded);if(loaded.size()==patch.size()&&loaded.begin()->second.height()==eh&&loaded.begin()->second.width()==ew){patch=std::move(loaded);resumed=true;}}}catch(const std::exception&){resumed=false;}}}
if(!resumed&&kernel)kernel(patch,ctx);
if(!resumed&&options_.checkpoint)save_field_set_atomic(cp,patch,sig);
for(const auto&[name,p]:patch){auto&s=sums.at(name);auto&w=weights.at(name);for(std::size_t py=0;py<eh;++py){const auto gy=y0-halo+static_cast<std::int64_t>(py);const double wy=taper_axis(gy,y0,y1,options_.halo);if(wy<=0)continue;for(std::size_t px=0;px<ew;++px){const auto gx=x0-halo+static_cast<std::int64_t>(px);const double wx=taper_axis(gx,x0,x1,options_.halo);const double wt=wy*wx;if(wt<=0)continue;const auto q=map_sphere(gy,gx,static_cast<std::int64_t>(out_h),static_cast<std::int64_t>(out_w));const auto yy=static_cast<std::size_t>(q.y),xx=static_cast<std::size_t>(q.x);s(yy,xx)+=wt*static_cast<double>(p(py,px));w(yy,xx)+=wt;}}}
if(progress)progress->advance(level_path,1,resumed?ctx.path+" resumed":ctx.path);}}
FieldSet next;for(auto&[name,s]:sums){const auto&w=weights.at(name);RasterF r(out_h,out_w);for(std::size_t i=0;i<r.size();++i){const double ww=w.span()[i];if(!(ww>0))throw std::runtime_error("refinement stitch left uncovered cell");r.span()[i]=static_cast<float>(s.span()[i]/ww);}next.emplace(name,std::move(r));}const auto in_sig=field_set_signature(current),out_sig=field_set_signature(next);result.levels.push_back({level,out_w,out_h,tile_total,in_sig,out_sig});current=std::move(next);if(progress)progress->finish(level_path,"stitched full-resolution level");}
result.fields=std::move(current);return result;}
} // namespace worldgen
