#include "worldgen/topology.hpp"
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <deque>
#include <numeric>
#include <stdexcept>
#include <vector>
namespace worldgen {
CellIndex map_spherical_index(std::int64_t y,std::int64_t x,std::size_t h0,std::size_t w0){if(!h0||!w0)throw std::invalid_argument("empty topology");const auto h=static_cast<std::int64_t>(h0),w=static_cast<std::int64_t>(w0);while(y<0||y>=h){if(y<0){y=-y-1;x+=w/2;}if(y>=h){y=2*h-y-1;x+=w/2;}}x%=w;if(x<0)x+=w;return {y,x};}
static float bilinear_at(const RasterF&a,double sy,double sx){const auto y0=static_cast<std::int64_t>(std::floor(sy)),x0=static_cast<std::int64_t>(std::floor(sx));const double fy=sy-static_cast<double>(y0),fx=sx-static_cast<double>(x0);auto p00=map_spherical_index(y0,x0,a.height(),a.width()),p01=map_spherical_index(y0,x0+1,a.height(),a.width()),p10=map_spherical_index(y0+1,x0,a.height(),a.width()),p11=map_spherical_index(y0+1,x0+1,a.height(),a.width());auto get=[&](CellIndex p){return static_cast<double>(a(static_cast<std::size_t>(p.y),static_cast<std::size_t>(p.x)));};return static_cast<float>(get(p00)*(1-fy)*(1-fx)+get(p01)*(1-fy)*fx+get(p10)*fy*(1-fx)+get(p11)*fy*fx);}
RasterF SphericalRasterOps::resize_bilinear(const RasterF&a,std::size_t dh,std::size_t dw)const{check(a.height(),a.width());if(!dh||!dw)throw std::invalid_argument("resize target");RasterF out(dh,dw);for(std::size_t y=0;y<dh;++y){const double sy=(static_cast<double>(y)+.5)*static_cast<double>(a.height())/static_cast<double>(dh)-.5;for(std::size_t x=0;x<dw;++x){const double sx=(static_cast<double>(x)+.5)*static_cast<double>(a.width())/static_cast<double>(dw)-.5;out(y,x)=bilinear_at(a,sy,sx);}}return out;}
static std::vector<double> kernel(double sigma,double truncate){if(sigma<=0)return {1};const int r=std::max(1,static_cast<int>(std::ceil(truncate*sigma)));std::vector<double>k(static_cast<std::size_t>(2*r+1));double s=0;for(int i=-r;i<=r;++i){double v=std::exp(-.5*static_cast<double>(i*i)/(sigma*sigma));k[static_cast<std::size_t>(i+r)]=v;s+=v;}for(double&v:k)v/=s;return k;}
RasterF SphericalRasterOps::gaussian_filter(const RasterF&a,double sy,double sx,double truncate)const{check(a.height(),a.width());sy=std::max(0.,sy);sx=std::max(0.,sx);auto ky=kernel(sy,truncate),kx=kernel(sx,truncate);const int ry=static_cast<int>((ky.size()-1)/2),rx=static_cast<int>((kx.size()-1)/2);RasterF tmp(a.height(),a.width()),out(a.height(),a.width());for(std::size_t y=0;y<a.height();++y)for(std::size_t x=0;x<a.width();++x){double s=0;for(int j=-rx;j<=rx;++j){auto p=map_spherical_index(static_cast<std::int64_t>(y),static_cast<std::int64_t>(x)+j,a.height(),a.width());s+=kx[static_cast<std::size_t>(j+rx)]*a(static_cast<std::size_t>(p.y),static_cast<std::size_t>(p.x));}tmp(y,x)=static_cast<float>(s);}for(std::size_t y=0;y<a.height();++y)for(std::size_t x=0;x<a.width();++x){double s=0;for(int i=-ry;i<=ry;++i){auto p=map_spherical_index(static_cast<std::int64_t>(y)+i,static_cast<std::int64_t>(x),a.height(),a.width());s+=ky[static_cast<std::size_t>(i+ry)]*tmp(static_cast<std::size_t>(p.y),static_cast<std::size_t>(p.x));}out(y,x)=static_cast<float>(s);}return out;}
template<class T> static std::pair<RasterD,RasterD> grad_impl(const SphereGrid&g,const Raster<T>&a){if(a.height()!=g.height()||a.width()!=g.width())throw std::invalid_argument("shape mismatch");RasterD gy(a.height(),a.width()),gx(a.height(),a.width());for(std::size_t y=0;y<a.height();++y)for(std::size_t x=0;x<a.width();++x){auto n=map_spherical_index(static_cast<std::int64_t>(y)-1,static_cast<std::int64_t>(x),a.height(),a.width()),s=map_spherical_index(static_cast<std::int64_t>(y)+1,static_cast<std::int64_t>(x),a.height(),a.width()),w=map_spherical_index(static_cast<std::int64_t>(y),static_cast<std::int64_t>(x)-1,a.height(),a.width()),e=map_spherical_index(static_cast<std::int64_t>(y),static_cast<std::int64_t>(x)+1,a.height(),a.width());gy(y,x)=(static_cast<double>(a(static_cast<std::size_t>(s.y),static_cast<std::size_t>(s.x)))-static_cast<double>(a(static_cast<std::size_t>(n.y),static_cast<std::size_t>(n.x))))/(2*g.dy_km());gx(y,x)=(static_cast<double>(a(static_cast<std::size_t>(e.y),static_cast<std::size_t>(e.x)))-static_cast<double>(a(static_cast<std::size_t>(w.y),static_cast<std::size_t>(w.x))))/(2*g.dx_km(y));}return {std::move(gy),std::move(gx)};}
std::pair<RasterD,RasterD>SphericalRasterOps::metric_gradient(const RasterF&a)const{return grad_impl(g_,a);}std::pair<RasterD,RasterD>SphericalRasterOps::metric_gradient(const RasterD&a)const{return grad_impl(g_,a);}
RasterD SphericalRasterOps::divergence(const RasterF&u,const RasterF&v)const{check(u.height(),u.width());check(v.height(),v.width());RasterD out(u.height(),u.width());for(std::size_t y=0;y<u.height();++y){const double cp=std::max(std::cos(g_.lat(y)*kDegToRad),1e-12);for(std::size_t x=0;x<u.width();++x){auto w=map_spherical_index(static_cast<std::int64_t>(y),static_cast<std::int64_t>(x)-1,u.height(),u.width()),e=map_spherical_index(static_cast<std::int64_t>(y),static_cast<std::int64_t>(x)+1,u.height(),u.width());double du=(u(static_cast<std::size_t>(e.y),static_cast<std::size_t>(e.x))-u(static_cast<std::size_t>(w.y),static_cast<std::size_t>(w.x)))/(2*g_.dx_km(y));double dv;if(y==0&&u.height()>=3)dv=(-3*v(0,x)*std::cos(g_.lat(0)*kDegToRad)+4*v(1,x)*std::cos(g_.lat(1)*kDegToRad)-v(2,x)*std::cos(g_.lat(2)*kDegToRad))/(2*g_.dy_km());else if(y+1==u.height()&&u.height()>=3){auto h=u.height();dv=(3*v(h-1,x)*std::cos(g_.lat(h-1)*kDegToRad)-4*v(h-2,x)*std::cos(g_.lat(h-2)*kDegToRad)+v(h-3,x)*std::cos(g_.lat(h-3)*kDegToRad))/(2*g_.dy_km());}else{const auto yn=y-1,ys=y+1;dv=(v(ys,x)*std::cos(g_.lat(ys)*kDegToRad)-v(yn,x)*std::cos(g_.lat(yn)*kDegToRad))/(2*g_.dy_km());}out(y,x)=du+dv/cp;}}return out;}
RasterD SphericalRasterOps::curl(const RasterF&u,const RasterF&v)const{check(u.height(),u.width());check(v.height(),v.width());RasterD out(u.height(),u.width());for(std::size_t y=0;y<u.height();++y){const double cp=std::max(std::cos(g_.lat(y)*kDegToRad),1e-12);for(std::size_t x=0;x<u.width();++x){auto w=map_spherical_index(static_cast<std::int64_t>(y),static_cast<std::int64_t>(x)-1,u.height(),u.width()),e=map_spherical_index(static_cast<std::int64_t>(y),static_cast<std::int64_t>(x)+1,u.height(),u.width());double dvx=(v(static_cast<std::size_t>(e.y),static_cast<std::size_t>(e.x))-v(static_cast<std::size_t>(w.y),static_cast<std::size_t>(w.x)))/(2*g_.dx_km(y));double duy;if(y==0&&u.height()>=3)duy=(-3*u(0,x)*std::cos(g_.lat(0)*kDegToRad)+4*u(1,x)*std::cos(g_.lat(1)*kDegToRad)-u(2,x)*std::cos(g_.lat(2)*kDegToRad))/(2*g_.dy_km());else if(y+1==u.height()&&u.height()>=3){auto h=u.height();duy=(3*u(h-1,x)*std::cos(g_.lat(h-1)*kDegToRad)-4*u(h-2,x)*std::cos(g_.lat(h-2)*kDegToRad)+u(h-3,x)*std::cos(g_.lat(h-3)*kDegToRad))/(2*g_.dy_km());}else{const auto yn=y-1,ys=y+1;duy=(u(ys,x)*std::cos(g_.lat(ys)*kDegToRad)-u(yn,x)*std::cos(g_.lat(yn)*kDegToRad))/(2*g_.dy_km());}out(y,x)=duy/cp-dvx;}}return out;}
RasterBool SphericalRasterOps::binary_dilation(const RasterBool&m,int n)const{check(m.height(),m.width());RasterBool out=m;for(int it=0;it<std::max(0,n);++it){RasterBool src=out;for(std::size_t y=0;y<m.height();++y)for(std::size_t x=0;x<m.width();++x)if(!src(y,x)){bool on=false;for(int dy=-1;dy<=1&&!on;++dy)for(int dx=-1;dx<=1;++dx)if(dy||dx){auto p=map_spherical_index(static_cast<std::int64_t>(y)+dy,static_cast<std::int64_t>(x)+dx,m.height(),m.width());if(src(static_cast<std::size_t>(p.y),static_cast<std::size_t>(p.x))){on=true;break;}}out(y,x)=static_cast<std::uint8_t>(on);}}return out;}
RasterBool SphericalRasterOps::binary_erosion(const RasterBool&m,int n)const{check(m.height(),m.width());RasterBool out=m;for(int it=0;it<std::max(0,n);++it){RasterBool src=out;for(std::size_t y=0;y<m.height();++y)for(std::size_t x=0;x<m.width();++x)if(src(y,x)){bool on=true;for(int dy=-1;dy<=1&&on;++dy)for(int dx=-1;dx<=1;++dx)if(dy||dx){auto p=map_spherical_index(static_cast<std::int64_t>(y)+dy,static_cast<std::int64_t>(x)+dx,m.height(),m.width());if(!src(static_cast<std::size_t>(p.y),static_cast<std::size_t>(p.x))){on=false;break;}}out(y,x)=static_cast<std::uint8_t>(on);}}return out;}
RasterBool SphericalRasterOps::boundary(const RasterBool&m)const{auto e=binary_erosion(m,1);RasterBool b(m.height(),m.width());for(std::size_t i=0;i<m.size();++i)b.span()[i]=static_cast<std::uint8_t>(m.span()[i]&&!e.span()[i]);return b;}
std::pair<RasterI32,std::int32_t>SphericalRasterOps::connected_components(const RasterBool&m)const{check(m.height(),m.width());RasterI32 lab(m.height(),m.width(),0);std::int32_t id=0;std::deque<std::pair<std::size_t,std::size_t>>q;for(std::size_t sy=0;sy<m.height();++sy)for(std::size_t sx=0;sx<m.width();++sx){if(!m(sy,sx)||lab(sy,sx))continue;++id;lab(sy,sx)=id;q.push_back({sy,sx});while(!q.empty()){auto[y,x]=q.front();q.pop_front();for(int dy=-1;dy<=1;++dy)for(int dx=-1;dx<=1;++dx)if(dy||dx){auto p=map_spherical_index(static_cast<std::int64_t>(y)+dy,static_cast<std::int64_t>(x)+dx,m.height(),m.width());auto yy=static_cast<std::size_t>(p.y),xx=static_cast<std::size_t>(p.x);if(m(yy,xx)&&!lab(yy,xx)){lab(yy,xx)=id;q.push_back({yy,xx});}}}}return {std::move(lab),id};}
template<class T> static RasterF norm01(const Raster<T>&a,bool robust){std::vector<double>v;v.reserve(a.size());for(auto z:a.span())if(std::isfinite(static_cast<double>(z)))v.push_back(static_cast<double>(z));RasterF out(a.height(),a.width(),0);if(v.empty())return out;double lo,hi;if(robust){std::sort(v.begin(),v.end());auto idx=[&](double q){return std::min(v.size()-1,static_cast<std::size_t>(q*static_cast<double>(v.size()-1)));};lo=v[idx(.01)];hi=v[idx(.99)];}else{auto mm=std::minmax_element(v.begin(),v.end());lo=*mm.first;hi=*mm.second;}if(!(hi>lo))return out;for(std::size_t i=0;i<a.size();++i){double z=static_cast<double>(a.span()[i]);out.span()[i]=std::isfinite(z)?static_cast<float>(std::clamp((z-lo)/(hi-lo),0.,1.)):0;}return out;}
RasterF normalize01(const RasterF&a,bool r){return norm01(a,r);}RasterF normalize01(const RasterD&a,bool r){return norm01(a,r);}
} // namespace worldgen
